from BaseClasses import ItemClassification as IC

from ..data_structures import ItemData

essences: dict[str, ItemData] = {  # TODO Aether essences
    "Whisper of the gods x5": ItemData(  # I found 120 essences in 0.1.0 (not counting Somu)
        classification=IC.useful,
        item_quantity=5,
        pool_quantity=24,
        game_name="chest-ess-1-whisper",
        item_type="Craft (limited)",
    ),
    "Verse of the Gods": ItemData(  # 3 in 0.1.0 (not counting Somu)
        classification=IC.useful,
        item_quantity=3,
        game_name="chest-ess-2-verse",
        item_type="Craft (limited)",
    ),
    "Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ball-ess",
        item_type="Craft",
    ),
    "Arma Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-armor-ball",
        item_type="Craft",
    ),
    "Pilo Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hair-ball",
        item_type="Craft",
    ),
    "Vespa Essence x5": ItemData(  # TODO game name
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="wasp-ess",
        item_type="Craft",
    ),
    "Turri Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="flower-ess",
        item_type="Craft",
    ),
    "Custo Turri Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="guard-flower-ess",
        item_type="Craft",
    ),
    "Ericius Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-hedgebird",
        item_type="Craft",
    ),
    "Testudo Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-turtle",
        item_type="Craft",
    ),
    "Rana Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-frog",
        item_type="Craft",
    ),
    "Pendicis Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-flyfish",
        item_type="Craft",
    ),
    "Aranea Mu Essence": ItemData(
        classification=IC.useful,  # Only 2 of those in 0.1.0
        item_quantity=1,
        pool_quantity=2,
        game_name="ess-common-spider",
        item_type="Craft (limited)",
    ),
    "Algae Dolus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-algae",
        item_type="Craft",
    ),
    "Molis Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-molerat",
        item_type="Craft",
    ),
    "Papilium Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-butterflybird",
        item_type="Craft",
    ),
    "Bovarks Essence x3": ItemData(
        classification=IC.filler,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-bowcow",
        item_type="Craft",
    ),
    "Carota Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-evil-garrot",
        item_type="Craft",
    ),
    "Pullu Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-bamboo",
        item_type="Craft",
    ),
    "Fern Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-water-plant",
        item_type="Craft",
    ),
    "Crista Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hexa-plant",
        item_type="Craft",
    ),
    "Curcur Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-pumpkin",
        item_type="Craft",
    ),
}
