"""Enemy, fauna and divine essences. Item ID band: 1200-1499"""

from BaseClasses import ItemClassification as IC

from ..data_structures import ItemData

essences: dict[str, ItemData] = {  # TODO Aether essences
    "Whisper of the gods x10": ItemData(  # I found 120 essences in 0.1.0 (not counting Somu)
        classification=IC.useful,
        item_quantity=10,
        pool_quantity=10,
        game_name="chest-ess-1-whisper",
        item_type="Craft (limited)",
        item_id=1200,
    ),
    "Verse of the Gods": ItemData(  # 3 in 0.1.0 (not counting Somu)
        classification=IC.useful,
        item_quantity=3,
        game_name="chest-ess-2-verse",
        item_type="Craft (limited)",
        item_id=1201,
    ),
    "Shard of Order x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="dng-ess-aether",
        item_type="Craft",
        item_id=1210,
    ),
    "Shard of Wisdom x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="dng-ess-cryo",
        item_type="Craft",
        item_id=1211,
    ),
    "Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ball-ess",
        item_type="Craft",
        item_id=1220,
    ),
    "Arma Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-armor-ball",
        item_type="Craft",
        item_id=1221,
    ),
    "Pilo Sphera Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hair-ball",
        item_type="Craft",
        item_id=1222,
    ),
    "Vespa Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="wasp-ess",
        item_type="Craft",
        item_id=1223,
    ),
    "Turri Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="flower-ess",
        item_type="Craft",
        item_id=1224,
    ),
    "Custo Turri Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="guard-flower-ess",
        item_type="Craft",
        item_id=1225,
    ),
    "Ericius Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hedgebird",
        item_type="Craft",
        item_id=1226,
    ),
    "Testudo Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-turtle",
        item_type="Craft",
        item_id=1227,
    ),
    "Rana Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-frog",
        item_type="Craft",
        item_id=1228,
    ),
    "Pendicis Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-flyfish",
        item_type="Craft",
        item_id=1229,
    ),
    "Aranea Mu Essence": ItemData(  # Only dropped by unique enemies, and one is removed in the rando
        classification=IC.useful,
        item_quantity=1,
        pool_quantity=1,
        game_name="ess-common-spider",
        item_type="Craft",
        item_id=1230,
    ),
    "Algae Dolus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-algae",
        item_type="Craft",
        item_id=1231,
    ),
    "Molis Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-molerat",
        item_type="Craft",
        item_id=1232,
    ),
    "Papilium Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-butterflybird",
        item_type="Craft",
        item_id=1233,
    ),
    "Bovarks Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-bowcow",
        item_type="Craft",
        item_id=1234,
    ),
    "Funis Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-axolotl",
        item_type="Craft",
        item_id=1235,
    ),
    "Limus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-slime",
        item_type="Craft",
        item_id=1236,
    ),
    "Boletus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-fungus",
        item_type="Craft",
        item_id=1237,
    ),
    "Laceta Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-banana-lizard",
        item_type="Craft",
        item_id=1238,
    ),
    "Suffolo Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-balloon",
        item_type="Craft",
        item_id=1239,
    ),
    "Plagato Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-platapus",
        item_type="Craft",
        item_id=1240,
    ),
    "Scorpio Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-scorpio",
        item_type="Craft",
        item_id=1241,
    ),
    "Carota Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-evil-garrot",
        item_type="Craft",
        item_id=1350,
    ),
    "Pullu Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-bamboo",
        item_type="Craft",
        item_id=1351,
    ),
    "Fern Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-water-plant",
        item_type="Craft",
        item_id=1352,
    ),
    "Crista Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hexa-plant",
        item_type="Craft",
        item_id=1353,
    ),
    "Curcur Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-pumpkin",
        item_type="Craft",
        item_id=1354,
    ),
    "Aspar Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-asparagus",
        item_type="Craft",
        item_id=1355,
    ),
    "Fungus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-mushroom",
        item_type="Craft",
        item_id=1356,
    ),
    "Cauda Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-cattail",
        item_type="Craft",
        item_id=1357,
    ),
    "Palus Essence x5": ItemData(
        classification=IC.filler,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-swampplant",
        item_type="Craft",
        item_id=1358,
    ),
}
