"""Blueprints and constructs for gems. Item ID band: 900-1199"""

from BaseClasses import ItemClassification as IC

from ..data_structures import ItemData

gem_recipies: dict[str, ItemData] = {
    "Blood Eye Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-min-aff",
        item_type="Construct",
        item_id=900,
    ),
    "Shatter End Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-min-breaker",
        item_type="Construct",
        item_id=901,
    ),
    "Dual Breach Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-brkdmg",
        item_type="Construct",
        item_id=927,
    ),
    "Daring Joust Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-cntrdmg",
        item_type="Construct",
        item_id=928,
    ),
    "Chaotic Tip Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-min-ampli",
        item_type="Construct",
        item_id=902,
    ),
    "Finishing Touch Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-finisher",
        item_type="Construct",
        item_id=903,
    ),
    "Double Trouble Construct": ItemData(
        classification=IC.useful,
        game_name="bp-mel-brkdmg",
        item_type="Construct",
        item_id=904,
    ),
    "Hydro Power Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rng-hydration",
        item_type="Construct",
        item_id=929,
    ),
    "Bloody Scar Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rang-min-snip",
        item_type="Construct",
        item_id=905,
    ),
    "High Ground Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rang-min-highground",
        item_type="Construct",
        item_id=906,
    ),
    "Fly Swatter Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rng-min-wing",
        item_type="Construct",
        item_id=907,
    ),
    "Stem Pecker Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rng-min-root",
        item_type="Construct",
        item_id=908,
    ),
    "Bully Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rng-min-bul",
        item_type="Construct",
        item_id=909,
    ),
    "Steady Zeal Construct": ItemData(
        classification=IC.useful,
        game_name="bp-rng-min-dp",
        item_type="Construct",
        item_id=910,
    ),
    "Verdant Guard Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-defl",
        item_type="Construct",
        item_id=911,
    ),
    "Libra's Blessing Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-aether",
        item_type="Construct",
        item_id=912,
    ),
    "Marquin's Blessing Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-ignis",
        item_type="Construct",
        item_id=919,
    ),
    "Blood Heart Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-crit",
        item_type="Construct",
        item_id=913,
    ),
    "Tireless Boulder Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-stam",
        item_type="Construct",
        item_id=914,
    ),
    "Lucky Reflex Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-critdef",
        item_type="Construct",
        item_id=915,
    ),
    "Feline's Gaze Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-hazdef",
        item_type="Construct",
        item_id=916,
    ),
    "Sharp Gravel Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-grit",
        item_type="Construct",
        item_id=917,
    ),
    "Cathartic Cleanse Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-balance",  # Forged into cor-min-status-heal-01
        item_type="Construct",
        item_id=918,
    ),
    "Stalwart Advance Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-autogrd",
        item_type="Construct",
        item_id=920,
    ),
    "Layered Fold Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-rangedef",
        item_type="Construct",
        item_id=921,
    ),
    "Fearless Zeal Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-pevadedp",
        item_type="Construct",
        item_id=922,
    ),
    "Mentor's Trill Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-exp-boost",
        item_type="Construct",
        item_id=923,
    ),
    "Basic Survival Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-health",
        item_type="Construct",
        item_id=924,
    ),
    "Apothecary Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-item-hp",
        item_type="Construct",
        item_id=925,
    ),
    "Due Appetite Construct": ItemData(
        classification=IC.useful,
        game_name="bp-cor-min-buffdur",
        item_type="Construct",
        item_id=926,
    ),
    "Chipped Edge Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mel-str",
        item_type="Blueprint",
        item_id=1000,
    ),
    "Bent Edge Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mel-crit",
        item_type="Blueprint",
        item_id=1001,
    ),
    "Humble Edge Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mel-spec",
        item_type="Blueprint",
        item_id=1002,
    ),
    "Shaggy Quill Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-rng-str",
        item_type="Blueprint",
        item_id=1003,
    ),
    "Fickle Quill Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-rng-crit",
        item_type="Blueprint",
        item_id=1004,
    ),
    "Dirty Quill Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-rng-spec",
        item_type="Blueprint",
        item_id=1005,
    ),
    "Dim Halo Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-up-maj-l-def",
        item_type="Blueprint",
        item_id=1006,
    ),
    "Vexed Halo Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-up-maj-l-off",
        item_type="Blueprint",
        item_id=1007,
    ),
    "Aged Laurel Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-up-maj-r-def",
        item_type="Blueprint",
        item_id=1008,
    ),
    "Crude Laurel Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-up-maj-r-off",
        item_type="Blueprint",
        item_id=1009,
    ),
    "Flexing Bracer Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mid-maj-l-off",
        item_type="Blueprint",
        item_id=1010,
    ),
    "Stiff Bracer Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mid-maj-l-def",
        item_type="Blueprint",
        item_id=1011,
    ),
    "Ruffian's Gauntlet Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mid-maj-r-off",
        item_type="Blueprint",
        item_id=1012,
    ),
    "Plebeian Gauntlet Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-mid-maj-r-def",
        item_type="Blueprint",
        item_id=1013,
    ),
    "Brittle Shell Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-low-maj-l-def",
        item_type="Blueprint",
        item_id=1014,
    ),
    "Light Shell Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-low-maj-l-off",
        item_type="Blueprint",
        item_id=1015,
    ),
    "Simple Cuirass Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-low-maj-r-def",
        item_type="Blueprint",
        item_id=1016,
    ),
    "Runner's Cuirass Blueprint": ItemData(
        classification=IC.useful,
        pool_quantity=0,
        game_name="bp-low-maj-r-off",
        item_type="Blueprint",
        item_id=1017,
    ),
}
