"""Minor gems. Item ID band: 300-599"""

from BaseClasses import ItemClassification as IC

from ..data_structures import ItemData

minor_gems: dict[str, ItemData] = {
    "Blood Eye": ItemData(
        classification=IC.useful,
        game_name="mel-min-aff-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=300,
    ),
    "Shatter End": ItemData(
        classification=IC.useful,
        game_name="mel-min-break-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=305,
    ),
    "Dual Breach": ItemData(
        classification=IC.useful,
        game_name="mel-min-brkdmg-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=320,
    ),
    "Daring Joust": ItemData(
        classification=IC.useful,
        game_name="mel-min-cntrdmg-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=390,
    ),
    "Chaotic Tip": ItemData(
        classification=IC.useful,
        game_name="mel-min-ampli-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=310,
    ),
    "Finishing Touch": ItemData(
        classification=IC.useful,
        game_name="mel-min-finisher-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=315,
    ),
    #"Aegis Wrath": ItemData(
    #    classification=IC.useful,
    #    game_name="mel-min-parrydmg-01",
    #    item_type="Minor Gem",
    #    pool_quantity=0,
    #    item_id=395,
    #),
    #"Cutting Edge": ItemData(
    #    classification=IC.useful,
    #    game_name="mel-min-charge-dmg-01",
    #    item_type="Minor Gem",
    #    pool_quantity=0,
    #    item_id=400,
    #),
    #"Polished Armament": ItemData(
    #    classification=IC.useful,
    #    game_name="mel-min-exp-01",
    #    item_type="Minor Gem",
    #    pool_quantity=0,
    #    item_id=405,
    #),
    "Bloody Scar": ItemData(
        classification=IC.useful,
        game_name="rng-min-snipe-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=325,
    ),
    "High Ground": ItemData(
        classification=IC.useful,
        game_name="rng-min-highground-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=330,
    ),
    "Hydro Power": ItemData(
        classification=IC.useful,
        game_name="rng-min-hydration-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=410,
    ),
    "Fly Swatter": ItemData(
        classification=IC.useful,
        game_name="rng-min-fly-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=335,
    ),
    "Stem Pecker": ItemData(
        classification=IC.useful,
        game_name="rng-min-root-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=340,
    ),
    "Bully": ItemData(
        classification=IC.useful,
        game_name="rng-min-bul-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=345,
    ),
    "Steady Zeal": ItemData(
        classification=IC.useful,
        game_name="rng-min-dp-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=350,
    ),
    "Verdant Guard": ItemData(
        classification=IC.useful,
        game_name="cor-min-defl-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=355,
    ),
    "Libra's Blessing": ItemData(
        classification=IC.useful,
        game_name="cor-min-aether-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=360,
    ),
    "Marquin's Blessing": ItemData(
        classification=IC.useful,
        game_name="cor-min-ignis-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=415,
    ),
    "Blood Heart": ItemData(
        classification=IC.useful,
        game_name="cor-min-crit-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=365,
    ),
    "Tireless Boulder": ItemData(
        classification=IC.useful,
        game_name="cor-min-stam-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=370,
    ),
    "Lucky Reflex": ItemData(
        classification=IC.useful,
        game_name="cor-min-critdef-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=375,
    ),
    "Feline's Gaze": ItemData(
        classification=IC.useful,
        game_name="cor-min-hazdef-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=380,
    ),
    "Sharp Gravel": ItemData(
        classification=IC.useful,
        game_name="cor-min-grit-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=385,
    ),
    "Stalwart Advance": ItemData(
        classification=IC.useful,
        game_name="cor-min-autogrd-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=420,
    ),
    "Layered Fold": ItemData(
        classification=IC.useful,
        game_name="cor-min-rangedef-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=425,
    ),
    "Fearless Zeal": ItemData(
        classification=IC.useful,
        game_name="cor-min-pevadedp-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=430,
    ),
    "Mentor's Trill": ItemData(
        classification=IC.useful,
        game_name="cor-min-exp-boost-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=435,
    ),
    "Cathartic Cleanse": ItemData(
        classification=IC.useful,
        game_name="cor-min-status-heal-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=440,
    ),
    "Apothecary": ItemData(
        classification=IC.useful,
        game_name="cor-min-item-hp-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=445,
    ),
    "Due Appetite": ItemData(
        classification=IC.useful,
        game_name="cor-min-item-buffdur-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=450,
    ),
    "Basic Survival": ItemData(
        classification=IC.useful,
        game_name="cor-min-health-01",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=455,
    ),
}
