"""Minor gems. Item ID band: 300-599"""

from BaseClasses import ItemClassification as IC

from ..data_structures import ItemData

minor_gems: dict[str, ItemData] = {
    "Blood Eye": ItemData(
        classification=IC.useful,
        game_name="mel-min-aff-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=300,
    ),
    "Shatter End": ItemData(
        classification=IC.useful,
        game_name="mel-min-breaker-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=305,
    ),
    "Amplifier": ItemData(
        classification=IC.useful,
        game_name="mel-min-ampli-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=310,
    ),
    "Finishing Touch": ItemData(
        classification=IC.useful,
        game_name="mel-finisher-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=315,
    ),
    "Double Trouble": ItemData(
        classification=IC.useful,
        game_name="mel-brkdmg-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=320,
    ),
    "Distant Mark": ItemData(
        classification=IC.useful,
        game_name="rang-min-snip-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=325,
    ),
    "High Ground": ItemData(
        classification=IC.useful,
        game_name="rang-min-highground-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=330,
    ),
    "Fly Swatter": ItemData(
        classification=IC.useful,
        game_name="rng-min-wing-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=335,
    ),
    "Stem Pecker": ItemData(
        classification=IC.useful,
        game_name="rng-min-root-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=340,
    ),
    "Bully": ItemData(
        classification=IC.useful,
        game_name="rng-min-bul-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=345,
    ),
    "Steady Zeal": ItemData(
        classification=IC.useful,
        game_name="rng-min-dp-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=350,
    ),
    "Verdant Guard": ItemData(
        classification=IC.useful,
        game_name="cor-min-defl-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=355,
    ),
    "Libra's Blessing": ItemData(
        classification=IC.useful,
        game_name="cor-min-aether-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=360,
    ),
    "Blood Heart": ItemData(
        classification=IC.useful,
        game_name="cor-min-crit-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=365,
    ),
    "Tireless Boulder": ItemData(
        classification=IC.useful,
        game_name="cor-min-stam-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=370,
    ),
    "Lucky Reflex": ItemData(
        classification=IC.useful,
        game_name="cor-min-critdef-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=375,
    ),
    "Feline's Gaze": ItemData(
        classification=IC.useful,
        game_name="cor-min-hazdef-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=380,
    ),
    "Grit": ItemData(
        classification=IC.useful,
        game_name="cor-min-grit-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=385,
    ),
    "Cleanse": ItemData(
        classification=IC.useful,
        game_name="cor-min-balance-1",
        item_type="Minor Gem",
        pool_quantity=0,
        item_id=390,
    ),
}
