"""Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `item_maps.py` with `item_data_ap`."""

from BaseClasses import ItemClassification as IC

from .data_structures import APItem

items: dict[str, APItem] = {
    "Test": APItem(id=1, quantity=0, classification=IC(2)),
    "Physis": APItem(id=2, quantity=0, classification=IC(3)),
    "Aether": APItem(id=3, quantity=1, classification=IC(3)),
    "Sword": APItem(id=4, quantity=0, classification=IC(3)),
    "Hammer": APItem(id=5, quantity=1, classification=IC(3)),
    "Crossbow": APItem(id=6, quantity=0, classification=IC(3)),
    "Chakram": APItem(id=7, quantity=1, classification=IC(3)),
    "Kama": APItem(id=8, quantity=1, classification=IC(3)),
    "Lyhamn level": APItem(id=9, quantity=1, classification=IC(3)),
    "Valley bridges repaired": APItem(id=10, quantity=1, classification=IC(1)),
    "Low tide": APItem(id=11, quantity=1, classification=IC(1)),
    "Boat travel": APItem(id=12, quantity=1, classification=IC(1)),
    "Fulcrum Mark": APItem(id=13, quantity=2, classification=IC(1)),
    "Trial Mark": APItem(id=14, quantity=2, classification=IC(1)),
    "Divine Connection": APItem(id=15, quantity=1, classification=IC(2)),
    "Bramble Quake": APItem(id=16, quantity=1, classification=IC(2)),
    "Verdant Saw": APItem(id=17, quantity=1, classification=IC(2)),
    "Leaf Blades": APItem(id=18, quantity=1, classification=IC(2)),
    "Cragspike Salvo": APItem(id=19, quantity=1, classification=IC(2)),
    "Ring of Rocks": APItem(id=20, quantity=1, classification=IC(2)),
    "Boom Snare": APItem(id=21, quantity=1, classification=IC(2)),
    "Zapflash Slash": APItem(id=22, quantity=1, classification=IC(2)),
    "Crack Shock": APItem(id=23, quantity=1, classification=IC(2)),
    "Bolt Barrage": APItem(id=24, quantity=1, classification=IC(2)),
    "Stardrop Counter": APItem(id=25, quantity=1, classification=IC(2)),
    "Chipped Edge": APItem(id=26, quantity=1, classification=IC(2)),
    "Bent Edge": APItem(id=27, quantity=1, classification=IC(2)),
    "Ruff Edge": APItem(id=28, quantity=1, classification=IC(2)),
    "Shaggy Quill": APItem(id=29, quantity=1, classification=IC(2)),
    "Fickle Quill": APItem(id=30, quantity=1, classification=IC(2)),
    "Dirty Quill": APItem(id=31, quantity=1, classification=IC(2)),
    "Dim Halo": APItem(id=32, quantity=1, classification=IC(2)),
    "Vexed Halo": APItem(id=33, quantity=1, classification=IC(2)),
    "Spirit Laurel": APItem(id=34, quantity=1, classification=IC(2)),
    "Crude Laurel": APItem(id=35, quantity=1, classification=IC(2)),
    "Flexing Bracer": APItem(id=36, quantity=1, classification=IC(2)),
    "Stiff Bracer": APItem(id=37, quantity=1, classification=IC(2)),
    "Ruffian's Gauntlet": APItem(id=38, quantity=1, classification=IC(2)),
    "Plebian Gauntlet": APItem(id=39, quantity=1, classification=IC(2)),
    "Brittle Shell": APItem(id=40, quantity=1, classification=IC(2)),
    "Light Shell": APItem(id=41, quantity=1, classification=IC(2)),
    "Simple Cuirass": APItem(id=42, quantity=1, classification=IC(2)),
    "Runner's Cuirass": APItem(id=43, quantity=1, classification=IC(2)),
    "Blood Eye": APItem(id=44, quantity=0, classification=IC(2)),
    "Shatter End": APItem(id=45, quantity=0, classification=IC(2)),
    "Amplifier": APItem(id=46, quantity=0, classification=IC(2)),
    "Finishing Touch": APItem(id=47, quantity=0, classification=IC(2)),
    "Double Trouble": APItem(id=48, quantity=0, classification=IC(2)),
    "Distant Mark": APItem(id=49, quantity=0, classification=IC(2)),
    "High Ground": APItem(id=50, quantity=0, classification=IC(2)),
    "Fly Swatter": APItem(id=51, quantity=0, classification=IC(2)),
    "Stem Pecker": APItem(id=52, quantity=0, classification=IC(2)),
    "Bully": APItem(id=53, quantity=0, classification=IC(2)),
    "Steady Zeal": APItem(id=54, quantity=0, classification=IC(2)),
    "Verdant Guard": APItem(id=55, quantity=0, classification=IC(2)),
    "Libra's Blessing": APItem(id=56, quantity=0, classification=IC(2)),
    "Blood Heart": APItem(id=57, quantity=0, classification=IC(2)),
    "Tireless Boulder": APItem(id=58, quantity=0, classification=IC(2)),
    "Lucky Reflex": APItem(id=59, quantity=0, classification=IC(2)),
    "Feline's Gaze": APItem(id=60, quantity=0, classification=IC(2)),
    "Grit": APItem(id=61, quantity=0, classification=IC(2)),
    "Cleanse": APItem(id=62, quantity=0, classification=IC(2)),
    "Blood Eye Construct": APItem(id=63, quantity=1, classification=IC(2)),
    "Shatter End Construct": APItem(id=64, quantity=1, classification=IC(2)),
    "Amplifier Construct": APItem(id=65, quantity=1, classification=IC(2)),
    "Finishing Touch Construct": APItem(id=66, quantity=1, classification=IC(2)),
    "Double Trouble Construct": APItem(id=67, quantity=1, classification=IC(2)),
    "Distant Mark Construct": APItem(id=68, quantity=1, classification=IC(2)),
    "High Ground Construct": APItem(id=69, quantity=1, classification=IC(2)),
    "Fly Swatter Construct": APItem(id=70, quantity=1, classification=IC(2)),
    "Stem Pecker Construct": APItem(id=71, quantity=1, classification=IC(2)),
    "Bully Construct": APItem(id=72, quantity=1, classification=IC(2)),
    "Steady Zeal Construct": APItem(id=73, quantity=1, classification=IC(2)),
    "Verdant Guard Construct": APItem(id=74, quantity=1, classification=IC(2)),
    "Libra's Blessing Construct": APItem(id=75, quantity=1, classification=IC(2)),
    "Blood Heart Construct": APItem(id=76, quantity=1, classification=IC(2)),
    "Tireless Boulder Construct": APItem(id=77, quantity=1, classification=IC(2)),
    "Lucky Reflex Construct": APItem(id=78, quantity=1, classification=IC(2)),
    "Feline's Gaze Construct": APItem(id=79, quantity=1, classification=IC(2)),
    "Grit Construct": APItem(id=80, quantity=1, classification=IC(2)),
    "Cleanse Construct": APItem(id=81, quantity=1, classification=IC(2)),
    "Chipped Edge Blueprint": APItem(id=82, quantity=0, classification=IC(2)),
    "Bent Edge Blueprint": APItem(id=83, quantity=0, classification=IC(2)),
    "Ruff Edge Blueprint": APItem(id=84, quantity=0, classification=IC(2)),
    "Shaggy Quill Blueprint": APItem(id=85, quantity=0, classification=IC(2)),
    "Fickle Quill Blueprint": APItem(id=86, quantity=0, classification=IC(2)),
    "Dirty Quill Blueprint": APItem(id=87, quantity=0, classification=IC(2)),
    "Dim Halo Blueprint": APItem(id=88, quantity=0, classification=IC(2)),
    "Vexed Halo Blueprint": APItem(id=89, quantity=0, classification=IC(2)),
    "Spirit Laurel Blueprint": APItem(id=90, quantity=0, classification=IC(2)),
    "Crude Laurel Blueprint": APItem(id=91, quantity=0, classification=IC(2)),
    "Flexing Bracer Blueprint": APItem(id=92, quantity=0, classification=IC(2)),
    "Stiff Bracer Blueprint": APItem(id=93, quantity=0, classification=IC(2)),
    "Ruffian's Gauntlet Blueprint": APItem(id=94, quantity=0, classification=IC(2)),
    "Plebian Gauntlet Blueprint": APItem(id=95, quantity=0, classification=IC(2)),
    "Brittle Shell Blueprint": APItem(id=96, quantity=0, classification=IC(2)),
    "Light Shell Blueprint": APItem(id=97, quantity=0, classification=IC(2)),
    "Simple Cuirass Blueprint": APItem(id=98, quantity=0, classification=IC(2)),
    "Runner's Cuirass Blueprint": APItem(id=99, quantity=0, classification=IC(2)),
    "Basic Ration": APItem(id=100, quantity=1, classification=IC(2)),
    "Ring Ration": APItem(id=101, quantity=1, classification=IC(2)),
    "Scrambled Egg": APItem(id=102, quantity=1, classification=IC(2)),
    "Fried Rice": APItem(id=103, quantity=1, classification=IC(2)),
    "Ring Rolls": APItem(id=104, quantity=1, classification=IC(2)),
    "Grilled Salmo": APItem(id=105, quantity=1, classification=IC(2)),
    "Baked Prapple": APItem(id=106, quantity=1, classification=IC(2)),
    "Prapple Salad": APItem(id=107, quantity=1, classification=IC(2)),
    "Pickled Garrot": APItem(id=108, quantity=1, classification=IC(2)),
    "Garrot Soup": APItem(id=109, quantity=1, classification=IC(2)),
    "Fisher's Gift": APItem(id=110, quantity=1, classification=IC(2)),
    "Fieldfruit Bake": APItem(id=111, quantity=1, classification=IC(2)),
    "Up & Below": APItem(id=112, quantity=1, classification=IC(2)),
    "Clerry Roll": APItem(id=113, quantity=1, classification=IC(2)),
    "Frumato Rice": APItem(id=114, quantity=1, classification=IC(2)),
    "Whisper of the gods x5": APItem(id=115, quantity=24, classification=IC(2)),
    "Verse of the Gods": APItem(id=116, quantity=1, classification=IC(2)),
    "Sphera Essence x5": APItem(id=117, quantity=0, classification=IC(0)),
    "Arma Sphera Essence x5": APItem(id=118, quantity=0, classification=IC(0)),
    "Pilo Sphera Essence x5": APItem(id=119, quantity=0, classification=IC(0)),
    "Vespa Essence x5": APItem(id=120, quantity=0, classification=IC(0)),
    "Turri Essence x5": APItem(id=121, quantity=0, classification=IC(0)),
    "Custo Turri Essence x5": APItem(id=122, quantity=0, classification=IC(0)),
    "Ericius Essence x3": APItem(id=123, quantity=0, classification=IC(0)),
    "Testudo Essence x3": APItem(id=124, quantity=0, classification=IC(0)),
    "Rana Essence x5": APItem(id=125, quantity=0, classification=IC(0)),
    "Pendicis Essence x3": APItem(id=126, quantity=0, classification=IC(0)),
    "Aranea Mu Essence": APItem(id=127, quantity=2, classification=IC(2)),
    "Algae Dolus Essence x5": APItem(id=128, quantity=0, classification=IC(0)),
    "Molis Essence x3": APItem(id=129, quantity=0, classification=IC(0)),
    "Papilium Essence x3": APItem(id=130, quantity=0, classification=IC(0)),
    "Bovarks Essence x3": APItem(id=131, quantity=0, classification=IC(0)),
    "Carota Essence x5": APItem(id=132, quantity=0, classification=IC(0)),
    "Pullu Essence x5": APItem(id=133, quantity=0, classification=IC(0)),
    "Fern Essence x5": APItem(id=134, quantity=0, classification=IC(0)),
    "Crista Essence x5": APItem(id=135, quantity=0, classification=IC(0)),
    "Curcur Essence x5": APItem(id=136, quantity=0, classification=IC(0)),
}
