"""
Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `item_maps.py` with `item_data_ap`.
"""

from BaseClasses import ItemClassification as IC

from .data_structures import APItem

items: dict[str, APItem] = {
    "Test": APItem(id=456123156, quantity=0, classification=IC(2)),
    "Test2": APItem(id=456123157, quantity=0, classification=IC(2)),
    "Physis": APItem(id=1, quantity=0, classification=IC(3)),
    "Aether": APItem(id=2, quantity=1, classification=IC(3)),
    "Sword": APItem(id=10, quantity=0, classification=IC(3)),
    "Hammer": APItem(id=11, quantity=1, classification=IC(3)),
    "Crossbow": APItem(id=15, quantity=0, classification=IC(3)),
    "Chakram": APItem(id=16, quantity=1, classification=IC(3)),
    "Kama": APItem(id=17, quantity=1, classification=IC(3)),
    "Lyhamn level": APItem(id=30, quantity=1, classification=IC(3)),
    "Valley bridges": APItem(id=40, quantity=1, classification=IC(1)),
    "Low tide": APItem(id=41, quantity=1, classification=IC(1)),
    "Boat travel": APItem(id=42, quantity=1, classification=IC(1)),
    "Fulcrum Mark": APItem(id=100, quantity=2, classification=IC(1)),
    "Trial Mark": APItem(id=101, quantity=2, classification=IC(1)),
    "Divine Connection": APItem(id=150, quantity=1, classification=IC(2)),
    "Bramble Quake": APItem(id=1500, quantity=1, classification=IC(2)),
    "Verdant Saw": APItem(id=1501, quantity=1, classification=IC(2)),
    "Leaf Blades": APItem(id=1502, quantity=1, classification=IC(2)),
    "Cragspike Salvo": APItem(id=1503, quantity=1, classification=IC(2)),
    "Ring of Rocks": APItem(id=1504, quantity=1, classification=IC(2)),
    "Boom Snare": APItem(id=1550, quantity=1, classification=IC(2)),
    "Zapflash Slash": APItem(id=1551, quantity=1, classification=IC(2)),
    "Crack Shock": APItem(id=1552, quantity=1, classification=IC(2)),
    "Bolt Barrage": APItem(id=1553, quantity=1, classification=IC(2)),
    "Stardrop Counter": APItem(id=1554, quantity=1, classification=IC(2)),
    "Chipped Edge": APItem(id=600, quantity=1, classification=IC(2)),
    "Bent Edge": APItem(id=605, quantity=1, classification=IC(2)),
    "Ruff Edge": APItem(id=610, quantity=1, classification=IC(2)),
    "Shaggy Quill": APItem(id=615, quantity=1, classification=IC(2)),
    "Fickle Quill": APItem(id=620, quantity=1, classification=IC(2)),
    "Dirty Quill": APItem(id=625, quantity=1, classification=IC(2)),
    "Dim Halo": APItem(id=630, quantity=1, classification=IC(2)),
    "Vexed Halo": APItem(id=635, quantity=1, classification=IC(2)),
    "Spirit Laurel": APItem(id=640, quantity=1, classification=IC(2)),
    "Crude Laurel": APItem(id=645, quantity=1, classification=IC(2)),
    "Flexing Bracer": APItem(id=650, quantity=1, classification=IC(2)),
    "Stiff Bracer": APItem(id=655, quantity=1, classification=IC(2)),
    "Ruffian's Gauntlet": APItem(id=660, quantity=1, classification=IC(2)),
    "Plebian Gauntlet": APItem(id=665, quantity=1, classification=IC(2)),
    "Brittle Shell": APItem(id=670, quantity=1, classification=IC(2)),
    "Light Shell": APItem(id=675, quantity=1, classification=IC(2)),
    "Simple Cuirass": APItem(id=680, quantity=1, classification=IC(2)),
    "Runner's Cuirass": APItem(id=685, quantity=1, classification=IC(2)),
    "Blood Eye": APItem(id=300, quantity=0, classification=IC(2)),
    "Shatter End": APItem(id=305, quantity=0, classification=IC(2)),
    "Amplifier": APItem(id=310, quantity=0, classification=IC(2)),
    "Finishing Touch": APItem(id=315, quantity=0, classification=IC(2)),
    "Double Trouble": APItem(id=320, quantity=0, classification=IC(2)),
    "Distant Mark": APItem(id=325, quantity=0, classification=IC(2)),
    "High Ground": APItem(id=330, quantity=0, classification=IC(2)),
    "Fly Swatter": APItem(id=335, quantity=0, classification=IC(2)),
    "Stem Pecker": APItem(id=340, quantity=0, classification=IC(2)),
    "Bully": APItem(id=345, quantity=0, classification=IC(2)),
    "Steady Zeal": APItem(id=350, quantity=0, classification=IC(2)),
    "Verdant Guard": APItem(id=355, quantity=0, classification=IC(2)),
    "Libra's Blessing": APItem(id=360, quantity=0, classification=IC(2)),
    "Blood Heart": APItem(id=365, quantity=0, classification=IC(2)),
    "Tireless Boulder": APItem(id=370, quantity=0, classification=IC(2)),
    "Lucky Reflex": APItem(id=375, quantity=0, classification=IC(2)),
    "Feline's Gaze": APItem(id=380, quantity=0, classification=IC(2)),
    "Grit": APItem(id=385, quantity=0, classification=IC(2)),
    "Cleanse": APItem(id=390, quantity=0, classification=IC(2)),
    "Blood Eye Construct": APItem(id=900, quantity=1, classification=IC(2)),
    "Shatter End Construct": APItem(id=901, quantity=1, classification=IC(2)),
    "Amplifier Construct": APItem(id=902, quantity=1, classification=IC(2)),
    "Finishing Touch Construct": APItem(id=903, quantity=1, classification=IC(2)),
    "Double Trouble Construct": APItem(id=904, quantity=1, classification=IC(2)),
    "Distant Mark Construct": APItem(id=905, quantity=1, classification=IC(2)),
    "High Ground Construct": APItem(id=906, quantity=1, classification=IC(2)),
    "Fly Swatter Construct": APItem(id=907, quantity=1, classification=IC(2)),
    "Stem Pecker Construct": APItem(id=908, quantity=1, classification=IC(2)),
    "Bully Construct": APItem(id=909, quantity=1, classification=IC(2)),
    "Steady Zeal Construct": APItem(id=910, quantity=1, classification=IC(2)),
    "Verdant Guard Construct": APItem(id=911, quantity=1, classification=IC(2)),
    "Libra's Blessing Construct": APItem(id=912, quantity=1, classification=IC(2)),
    "Blood Heart Construct": APItem(id=913, quantity=1, classification=IC(2)),
    "Tireless Boulder Construct": APItem(id=914, quantity=1, classification=IC(2)),
    "Lucky Reflex Construct": APItem(id=915, quantity=1, classification=IC(2)),
    "Feline's Gaze Construct": APItem(id=916, quantity=1, classification=IC(2)),
    "Grit Construct": APItem(id=917, quantity=1, classification=IC(2)),
    "Cleanse Construct": APItem(id=918, quantity=0, classification=IC(2)),
    "Chipped Edge Blueprint": APItem(id=1000, quantity=0, classification=IC(2)),
    "Bent Edge Blueprint": APItem(id=1001, quantity=0, classification=IC(2)),
    "Ruff Edge Blueprint": APItem(id=1002, quantity=0, classification=IC(2)),
    "Shaggy Quill Blueprint": APItem(id=1003, quantity=0, classification=IC(2)),
    "Fickle Quill Blueprint": APItem(id=1004, quantity=0, classification=IC(2)),
    "Dirty Quill Blueprint": APItem(id=1005, quantity=0, classification=IC(2)),
    "Dim Halo Blueprint": APItem(id=1006, quantity=0, classification=IC(2)),
    "Vexed Halo Blueprint": APItem(id=1007, quantity=0, classification=IC(2)),
    "Spirit Laurel Blueprint": APItem(id=1008, quantity=0, classification=IC(2)),
    "Crude Laurel Blueprint": APItem(id=1009, quantity=0, classification=IC(2)),
    "Flexing Bracer Blueprint": APItem(id=1010, quantity=0, classification=IC(2)),
    "Stiff Bracer Blueprint": APItem(id=1011, quantity=0, classification=IC(2)),
    "Ruffian's Gauntlet Blueprint": APItem(id=1012, quantity=0, classification=IC(2)),
    "Plebian Gauntlet Blueprint": APItem(id=1013, quantity=0, classification=IC(2)),
    "Brittle Shell Blueprint": APItem(id=1014, quantity=0, classification=IC(2)),
    "Light Shell Blueprint": APItem(id=1015, quantity=0, classification=IC(2)),
    "Simple Cuirass Blueprint": APItem(id=1016, quantity=0, classification=IC(2)),
    "Runner's Cuirass Blueprint": APItem(id=1017, quantity=0, classification=IC(2)),
    "Basic Ration": APItem(id=1700, quantity=0, classification=IC(2)),
    "Ring Ration": APItem(id=1701, quantity=1, classification=IC(2)),
    "Scrambled Egg": APItem(id=1702, quantity=1, classification=IC(2)),
    "Fried Rice": APItem(id=1703, quantity=0, classification=IC(2)),
    "Ring Rolls": APItem(id=1704, quantity=1, classification=IC(2)),
    "Grilled Salmo": APItem(id=1705, quantity=1, classification=IC(2)),
    "Baked Prapple": APItem(id=1706, quantity=1, classification=IC(2)),
    "Prapple Salad": APItem(id=1707, quantity=0, classification=IC(2)),
    "Pickled Garrot": APItem(id=1708, quantity=1, classification=IC(2)),
    "Garrot Soup": APItem(id=1709, quantity=1, classification=IC(2)),
    "Fisher's Gift": APItem(id=1710, quantity=0, classification=IC(2)),
    "Fieldfruit Bake": APItem(id=1711, quantity=1, classification=IC(2)),
    "Up & Below": APItem(id=1712, quantity=1, classification=IC(2)),
    "Clerry Roll": APItem(id=1713, quantity=1, classification=IC(2)),
    "Frumato Rice": APItem(id=1714, quantity=1, classification=IC(2)),
    "Whisper of the gods x10": APItem(id=1200, quantity=10, classification=IC(2)),
    "Verse of the Gods": APItem(id=1201, quantity=1, classification=IC(2)),
    "Shard of Order x5": APItem(id=1210, quantity=0, classification=IC(0)),
    "Sphera Essence x5": APItem(id=1220, quantity=0, classification=IC(0)),
    "Arma Sphera Essence x5": APItem(id=1221, quantity=0, classification=IC(0)),
    "Pilo Sphera Essence x5": APItem(id=1222, quantity=0, classification=IC(0)),
    "Vespa Essence x5": APItem(id=1223, quantity=0, classification=IC(0)),
    "Turri Essence x5": APItem(id=1224, quantity=0, classification=IC(0)),
    "Custo Turri Essence x5": APItem(id=1225, quantity=0, classification=IC(0)),
    "Ericius Essence x3": APItem(id=1226, quantity=0, classification=IC(0)),
    "Testudo Essence x3": APItem(id=1227, quantity=0, classification=IC(0)),
    "Rana Essence x5": APItem(id=1228, quantity=0, classification=IC(0)),
    "Pendicis Essence x3": APItem(id=1229, quantity=0, classification=IC(0)),
    "Aranea Mu Essence": APItem(id=1230, quantity=1, classification=IC(0)),
    "Algae Dolus Essence x5": APItem(id=1231, quantity=0, classification=IC(0)),
    "Molis Essence x3": APItem(id=1232, quantity=0, classification=IC(0)),
    "Papilium Essence x3": APItem(id=1233, quantity=0, classification=IC(0)),
    "Bovarks Essence x3": APItem(id=1234, quantity=0, classification=IC(0)),
    "Carota Essence x5": APItem(id=1350, quantity=0, classification=IC(0)),
    "Pullu Essence x5": APItem(id=1351, quantity=0, classification=IC(0)),
    "Fern Essence x5": APItem(id=1352, quantity=0, classification=IC(0)),
    "Crista Essence x5": APItem(id=1353, quantity=0, classification=IC(0)),
    "Curcur Essence x5": APItem(id=1354, quantity=0, classification=IC(0)),
}
