"""
Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `item_maps.py` with `item_groups_ap`.
"""

item_groups: dict[str, list[str]] = {
    "Filler": [
        "Shard of Order x5",
        "Shard of Wisdom x5",
        "Sphera Essence x5",
        "Arma Sphera Essence x5",
        "Pilo Sphera Essence x5",
        "Vespa Essence x5",
        "Turri Essence x5",
        "Custo Turri Essence x5",
        "Ericius Essence x5",
        "Testudo Essence x5",
        "Rana Essence x5",
        "Pendicis Essence x5",
        "Algae Dolus Essence x5",
        "Molis Essence x5",
        "Papilium Essence x5",
        "Bovarks Essence x5",
        "Funis Essence x5",
        "Limus Essence x5",
        "Boletus Essence x5",
        "Laceta Essence x5",
        "Suffolo Essence x5",
        "Plagato Essence x5",
        "Scorpio Essence x5",
        "Carota Essence x5",
        "Pullu Essence x5",
        "Fern Essence x5",
        "Crista Essence x5",
        "Curcur Essence x5",
        "Aspar Essence x5",
        "Fungus Essence x5",
        "Cauda Essence x5",
        "Palus Essence x5",
    ],
    "Element": [
        "Test",
        "Test2",
        "Physis",
        "Aether",
    ],
    "Melee weapon": [
        "Sword",
        "Hammer",
        "Spear",
    ],
    "Range weapon": [
        "Crossbow",
        "Chakram",
        "Kama",
    ],
    "Community level": [
        "Lyhamn level",
    ],
    "Area access": [
        "Valley bridges",
        "Low tide",
        "Boat travel",
    ],
    "Key": [
        "Fulcrum Mark",
        "Trial Mark",
        "Aether Trial Mark",
        "Cryo Trial Mark",
    ],
    "Upgrade": [
        "Divine Connection",
    ],
    "Divine Art": [
        "Bramble Quake",
        "Verdant Saw",
        "Leaf Blades",
        "Cragspike Salvo",
        "Ring of Rocks",
        "Boom Snare",
        "Zapflash Slash",
        "Crack Shock",
        "Bolt Barrage",
        "Stardrop Counter",
        "Frost Reaver",
    ],
    "Gem": [
        "Chipped Edge",
        "Bent Edge",
        "Humble Edge",
        "Shaggy Quill",
        "Fickle Quill",
        "Dirty Quill",
        "Dim Halo",
        "Vexed Halo",
        "Budding Halo",
        "Aged Laurel",
        "Crude Laurel",
        "Withering Laurel",
        "Flexing Bracer",
        "Stiff Bracer",
        "Flinger's Bracer",
        "Ruffian's Gauntlet",
        "Plebeian Gauntlet",
        "Glimmering Gauntlet",
        "Brittle Shell",
        "Light Shell",
        "Dubious Shell",
        "Simple Cuirass",
        "Runner's Cuirass",
        "Painted Cuirass",
    ],
    "Minor Gem": [
        "Blood Eye",
        "Shatter End",
        "Dual Breach",
        "Daring Joust",
        "Chaotic Tip",
        "Finishing Touch",
        "Bloody Scar",
        "High Ground",
        "Hydro Power",
        "Fly Swatter",
        "Stem Pecker",
        "Bully",
        "Steady Zeal",
        "Verdant Guard",
        "Libra's Blessing",
        "Marquin's Blessing",
        "Blood Heart",
        "Tireless Boulder",
        "Lucky Reflex",
        "Feline's Gaze",
        "Sharp Gravel",
        "Stalwart Advance",
        "Layered Fold",
        "Fearless Zeal",
        "Mentor's Trill",
        "Cathartic Cleanse",
        "Apothecary",
        "Due Appetite",
        "Basic Survival",
    ],
    "Construct": [
        "Blood Eye Construct",
        "Shatter End Construct",
        "Dual Breach Construct",
        "Daring Joust Construct",
        "Chaotic Tip Construct",
        "Finishing Touch Construct",
        "Double Trouble Construct",
        "Hydro Power Construct",
        "Bloody Scar Construct",
        "High Ground Construct",
        "Fly Swatter Construct",
        "Stem Pecker Construct",
        "Bully Construct",
        "Steady Zeal Construct",
        "Verdant Guard Construct",
        "Libra's Blessing Construct",
        "Marquin's Blessing Construct",
        "Blood Heart Construct",
        "Tireless Boulder Construct",
        "Lucky Reflex Construct",
        "Feline's Gaze Construct",
        "Sharp Gravel Construct",
        "Cathartic Cleanse Construct",
        "Stalwart Advance Construct",
        "Layered Fold Construct",
        "Fearless Zeal Construct",
        "Mentor's Trill Construct",
        "Basic Survival Construct",
        "Apothecary Construct",
        "Due Appetite Construct",
    ],
    "Blueprint": [
        "Chipped Edge Blueprint",
        "Bent Edge Blueprint",
        "Humble Edge Blueprint",
        "Shaggy Quill Blueprint",
        "Fickle Quill Blueprint",
        "Dirty Quill Blueprint",
        "Dim Halo Blueprint",
        "Vexed Halo Blueprint",
        "Aged Laurel Blueprint",
        "Crude Laurel Blueprint",
        "Flexing Bracer Blueprint",
        "Stiff Bracer Blueprint",
        "Ruffian's Gauntlet Blueprint",
        "Plebeian Gauntlet Blueprint",
        "Brittle Shell Blueprint",
        "Light Shell Blueprint",
        "Simple Cuirass Blueprint",
        "Runner's Cuirass Blueprint",
    ],
    "Dish Recipie": [
        "Basic Ration",
        "Ring Ration",
        "Scrambled Egg",
        "Fried Rice",
        "Ring Rolls",
        "Grilled Salmo",
        "Baked Prapple",
        "Prapple Salad",
        "Pickled Garrot",
        "Garrot Soup",
        "Fisher's Gift",
        "Fieldfruit Bake",
        "Up & Below",
        "Clerry Roll",
        "Frumato Rice",
        "Shroomlett",
        "Swanana Nut Chips",
        "Sour Gugumber",
    ],
    "Craft (limited)": [
        "Whisper of the gods x10",
        "Verse of the Gods",
    ],
    "Craft": [
        "Shard of Order x5",
        "Shard of Wisdom x5",
        "Sphera Essence x5",
        "Arma Sphera Essence x5",
        "Pilo Sphera Essence x5",
        "Vespa Essence x5",
        "Turri Essence x5",
        "Custo Turri Essence x5",
        "Ericius Essence x5",
        "Testudo Essence x5",
        "Rana Essence x5",
        "Pendicis Essence x5",
        "Aranea Mu Essence",
        "Algae Dolus Essence x5",
        "Molis Essence x5",
        "Papilium Essence x5",
        "Bovarks Essence x5",
        "Funis Essence x5",
        "Limus Essence x5",
        "Boletus Essence x5",
        "Laceta Essence x5",
        "Suffolo Essence x5",
        "Plagato Essence x5",
        "Scorpio Essence x5",
        "Carota Essence x5",
        "Pullu Essence x5",
        "Fern Essence x5",
        "Crista Essence x5",
        "Curcur Essence x5",
        "Aspar Essence x5",
        "Fungus Essence x5",
        "Cauda Essence x5",
        "Palus Essence x5",
    ],
}
