"""Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `item_maps.py` with `item_groups_ap`."""

item_groups: dict[str, list[str]] = {
    "Filler": [
        "Sphera Essence x5",
        "Arma Sphera Essence x5",
        "Pilo Sphera Essence x5",
        "Vespa Essence x5",
        "Turri Essence x5",
        "Custo Turri Essence x5",
        "Ericius Essence x3",
        "Testudo Essence x3",
        "Rana Essence x5",
        "Pendicis Essence x3",
        "Algae Dolus Essence x5",
        "Molis Essence x3",
        "Papilium Essence x3",
        "Bovarks Essence x3",
        "Carota Essence x5",
        "Pullu Essence x5",
        "Fern Essence x5",
        "Crista Essence x5",
        "Curcur Essence x5",
    ],
    "Element": [
        "Test",
        "Physis",
        "Aether",
    ],
    "Melee weapon": [
        "Sword",
        "Hammer",
    ],
    "Range weapon": [
        "Crossbow",
        "Chakram",
        "Kama",
    ],
    "Community level": [
        "Lyhamn level",
    ],
    "Area access": [
        "Valley bridges repaired",
        "Low tide",
        "Boat travel",
    ],
    "Key": [
        "Fulcrum Mark",
        "Trial Mark",
    ],
    "Upgrade": [
        "Divine Connection",
    ],
    "Divine Art": [
        "Bramble Quake",
        "Verdant Saw",
        "Leaf Blades",
        "Cragspike Salvo",
        "Ring of Rocks",
        "Boom Snare",
        "Zapflash Slash",
        "Crack Shock",
        "Bolt Barrage",
        "Stardrop Counter",
    ],
    "Gem": [
        "Chipped Edge",
        "Bent Edge",
        "Ruff Edge",
        "Shaggy Quill",
        "Fickle Quill",
        "Dirty Quill",
        "Dim Halo",
        "Vexed Halo",
        "Spirit Laurel",
        "Crude Laurel",
        "Flexing Bracer",
        "Stiff Bracer",
        "Ruffian's Gauntlet",
        "Plebian Gauntlet",
        "Brittle Shell",
        "Light Shell",
        "Simple Cuirass",
        "Runner's Cuirass",
    ],
    "Minor Gem": [
        "Blood Eye",
        "Shatter End",
        "Amplifier",
        "Finishing Touch",
        "Double Trouble",
        "Distant Mark",
        "High Ground",
        "Fly Swatter",
        "Stem Pecker",
        "Bully",
        "Steady Zeal",
        "Verdant Guard",
        "Libra's Blessing",
        "Blood Heart",
        "Tireless Boulder",
        "Lucky Reflex",
        "Feline's Gaze",
        "Grit",
        "Cleanse",
    ],
    "Construct": [
        "Blood Eye Construct",
        "Shatter End Construct",
        "Amplifier Construct",
        "Finishing Touch Construct",
        "Double Trouble Construct",
        "Distant Mark Construct",
        "High Ground Construct",
        "Fly Swatter Construct",
        "Stem Pecker Construct",
        "Bully Construct",
        "Steady Zeal Construct",
        "Verdant Guard Construct",
        "Libra's Blessing Construct",
        "Blood Heart Construct",
        "Tireless Boulder Construct",
        "Lucky Reflex Construct",
        "Feline's Gaze Construct",
        "Grit Construct",
        "Cleanse Construct",
    ],
    "Blueprint": [
        "Chipped Edge Blueprint",
        "Bent Edge Blueprint",
        "Ruff Edge Blueprint",
        "Shaggy Quill Blueprint",
        "Fickle Quill Blueprint",
        "Dirty Quill Blueprint",
        "Dim Halo Blueprint",
        "Vexed Halo Blueprint",
        "Spirit Laurel Blueprint",
        "Crude Laurel Blueprint",
        "Flexing Bracer Blueprint",
        "Stiff Bracer Blueprint",
        "Ruffian's Gauntlet Blueprint",
        "Plebian Gauntlet Blueprint",
        "Brittle Shell Blueprint",
        "Light Shell Blueprint",
        "Simple Cuirass Blueprint",
        "Runner's Cuirass Blueprint",
    ],
    "Dish Recipie": [
        "Basic Ration",
        "Ring Ration",
        "Scrambled Egg",
        "Fried Rice",
        "Ring Rolls",
        "Grilled Salmo",
        "Baked Prapple",
        "Prapple Salad",
        "Pickled Garrot",
        "Garrot Soup",
        "Fisher's Gift",
        "Fieldfruit Bake",
        "Up & Below",
        "Clerry Roll",
        "Frumato Rice",
    ],
    "Craft (limited)": [
        "Whisper of the gods x5",
        "Verse of the Gods",
        "Aranea Mu Essence",
    ],
    "Craft": [
        "Sphera Essence x5",
        "Arma Sphera Essence x5",
        "Pilo Sphera Essence x5",
        "Vespa Essence x5",
        "Turri Essence x5",
        "Custo Turri Essence x5",
        "Ericius Essence x3",
        "Testudo Essence x3",
        "Rana Essence x5",
        "Pendicis Essence x3",
        "Algae Dolus Essence x5",
        "Molis Essence x3",
        "Papilium Essence x3",
        "Bovarks Essence x3",
        "Carota Essence x5",
        "Pullu Essence x5",
        "Fern Essence x5",
        "Crista Essence x5",
        "Curcur Essence x5",
    ],
}
