from BaseClasses import ItemClassification as IC

from .data_structures import ItemData

# TODO Community levels: use the first level for regrowth / cleanse nest ?

items: dict[str, ItemData] = {
    "Test": ItemData(
        classification=IC.filler,
        id=56132,
        item_type="Element",
        game_name="test",
    ),
    "Physis": ItemData(
        classification=IC.progression | IC.useful,
        id=1,
        item_type="Element",
        pool_quantity=0,
        game_name="ELEMENT_NATURE",
    ),
    "Aether": ItemData(
        classification=IC.progression | IC.useful,
        id=2,
        item_type="Element",
        game_name="ELEMENT_AETHER",
    ),
    "Sword": ItemData(
        classification=IC.progression | IC.useful,
        id=11,
        item_type="Melee weapon",
        pool_quantity=0,
        game_name="WEAPON:sword",
    ),
    "Hammer": ItemData(
        classification=IC.progression | IC.useful,
        id=12,
        item_type="Melee weapon",
        game_name="WEAPON:hammer",
    ),
    "Crossbow": ItemData(
        classification=IC.progression | IC.useful,
        id=21,
        item_type="Range weapon",
        pool_quantity=0,
        game_name="WEAPON:crossbow",
    ),
    "Chakram": ItemData(
        classification=IC.progression | IC.useful,
        id=22,
        item_type="Range weapon",
        game_name="WEAPON:chakram",
    ),
    "Kama": ItemData(
        classification=IC.progression | IC.useful,
        id=23,
        item_type="Range weapon",
        game_name="WEAPON:kama",
    ),
    #"Filia": ItemData(
    #    classification=IC.progression | IC.useful,
    #    id=30,
    #    item_type="Party member",
    #    game_name="PARTY:filia",
    #),
    "Lyhamn level": ItemData(
        classification=IC.progression | IC.useful,
        id=40,
        item_type="Community level",
        game_name="CHANGE:lyhamn",
    ),
    "Valley bridges repaired": ItemData(
        classification=IC.progression,
        id=60,
        item_type="Area access",
        game_name="CHANGE:bridge",
    ),
    "Low tide": ItemData(
        classification=IC.progression,
        id=61,
        item_type="Area access",
        game_name="CHANGE:tide",
    ),
    "Boat travel": ItemData(
        classification=IC.progression,
        id=62,
        item_type="Area access",
        game_name="CHANGE:boat",
    ),
    "Fulcrum Mark": ItemData(
        classification=IC.progression,
        id=80,
        pool_quantity=2,
        game_name="the-key",
        item_type="Key",
    ),
    "Trial Mark": ItemData(
        classification=IC.progression,
        id=81,
        pool_quantity=2,
        game_name="the-key-dng",
        item_type="Key",
    ),
    "Whisper of the gods x5": ItemData(  # I found 120 essences in 0.1.0 (not counting Somu)
        classification=IC.useful,
        id=101,
        item_quantity=5,
        pool_quantity=24,
        game_name="chest-ess-1-whisper",
        item_type="Craft (limited)",
    ),
    "Verse of the Gods": ItemData(  # 3 in 0.1.0 (not counting Somu)
        classification=IC.useful,
        id=102,
        item_quantity=3,
        game_name="chest-ess-2-verse",
        item_type="Craft (limited)",
    ),
    "Sphera Essence x5": ItemData(
        classification=IC.filler,
        id=200,
        item_quantity=5,
        pool_quantity=0,
        game_name="ball-ess",
        item_type="Craft",
    ),
    "Arma Sphera Essence x5": ItemData(
        classification=IC.filler,
        id=201,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-armor-ball",
        item_type="Craft",
    ),
    "Pilo Sphera Essence x5": ItemData(
        classification=IC.filler,
        id=202,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hair-ball",
        item_type="Craft",
    ),
    "Vespa Essence x5": ItemData(  # TODO game name
        classification=IC.filler,
        id=203,
        item_quantity=5,
        pool_quantity=0,
        game_name="wasp-ess",
        item_type="Craft",
    ),
    "Turri Essence x5": ItemData(
        classification=IC.filler,
        id=204,
        item_quantity=5,
        pool_quantity=0,
        game_name="flower-ess",
        item_type="Craft",
    ),
    "Custo Turri Essence x5": ItemData(
        classification=IC.filler,
        id=205,
        item_quantity=5,
        pool_quantity=0,
        game_name="guard-flower-ess",
        item_type="Craft",
    ),
    "Ericius Essence x3": ItemData(
        classification=IC.filler,
        id=206,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-hedgebird",
        item_type="Craft",
    ),
    "Testudo Essence x3": ItemData(
        classification=IC.filler,
        id=207,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-turtle",
        item_type="Craft",
    ),
    "Rana Essence x5": ItemData(
        classification=IC.filler,
        id=208,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-frog",
        item_type="Craft",
    ),
    "Pendicis Essence x3": ItemData(
        classification=IC.filler,
        id=209,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-flyfish",
        item_type="Craft",
    ),
    "Aranea Mu Essence": ItemData(
        classification=IC.useful,  # Only 2 of those in 0.1.0
        id=210,
        item_quantity=1,
        pool_quantity=2,
        game_name="ess-common-spider",
        item_type="Craft (limited)",
    ),
    "Algae Dolus Essence x5": ItemData(
        classification=IC.filler,
        id=211,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-algae",
        item_type="Craft",
    ),
    "Molis Essence x3": ItemData(
        classification=IC.filler,
        id=212,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-molerat",
        item_type="Craft",
    ),
    "Papilium Essence x3": ItemData(
        classification=IC.filler,
        id=213,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-butterflybird",
        item_type="Craft",
    ),
    "Bovarks Essence x3": ItemData(
        classification=IC.filler,
        id=214,
        item_quantity=3,
        pool_quantity=0,
        game_name="ess-bowcow",
        item_type="Craft",
    ),
    "Carota Essence x5": ItemData(
        classification=IC.filler,
        id=300,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-evil-garrot",
        item_type="Craft",
    ),
    "Pullu Essence x5": ItemData(
        classification=IC.filler,
        id=301,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-bamboo",
        item_type="Craft",
    ),
    "Fern Essence x5": ItemData(
        classification=IC.filler,
        id=301,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-water-plant",
        item_type="Craft",
    ),
    "Crista Essence x5": ItemData(
        classification=IC.filler,
        id=301,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-hexa-plant",
        item_type="Craft",
    ),
    "Curcur Essence x5": ItemData(
        classification=IC.filler,
        id=301,
        item_quantity=5,
        pool_quantity=0,
        game_name="ess-pumpkin",
        item_type="Craft",
    ),
    "Chipped Edge": ItemData(
        classification=IC.useful,
        id=501,
        pool_quantity=1,
        game_name="mel-str-01",
        item_type="Gem",
    ),
    "Bent Edge": ItemData(
        classification=IC.useful,
        id=511,
        pool_quantity=1,
        game_name="mel-crit-01",
        item_type="Gem",
    ),
    "Ruff Edge": ItemData(
        classification=IC.useful,
        id=521,
        pool_quantity=1,
        game_name="mel-spec-01",
        item_type="Gem",
    ),
    "Shaggy Quill": ItemData(
        classification=IC.useful,
        id=531,
        pool_quantity=1,
        game_name="rng-str-01",
        item_type="Gem",
    ),
    "Fickle Quill": ItemData(
        classification=IC.useful,
        id=541,
        pool_quantity=1,
        game_name="rng-crit-01",
        item_type="Gem",
    ),
    "Dirty Quill": ItemData(
        classification=IC.useful,
        id=551,
        pool_quantity=1,
        game_name="rng-spec-01",
        item_type="Gem",
    ),
    "Dim Halo": ItemData(
        classification=IC.useful,
        id=561,
        pool_quantity=1,
        game_name="up-maj-l-def-01",
        item_type="Gem",
    ),
    "Vexed Halo": ItemData(
        classification=IC.useful,
        id=571,
        pool_quantity=1,
        game_name="up-maj-l-off-01",
        item_type="Gem",
    ),
    "Spirit Laurel": ItemData(
        classification=IC.useful,
        id=581,
        pool_quantity=1,
        game_name="up-maj-r-def-01",
        item_type="Gem",
    ),
    "Crude Laurel": ItemData(
        classification=IC.useful,
        id=591,
        pool_quantity=1,
        game_name="up-maj-r-off-01",
        item_type="Gem",
    ),
    "Flexing Bracer": ItemData(
        classification=IC.useful,
        id=601,
        pool_quantity=1,
        game_name="mid-maj-l-off-01",
        item_type="Gem",
    ),
    "Stiff Bracer": ItemData(
        classification=IC.useful,
        id=611,
        pool_quantity=1,
        game_name="mid-maj-l-def-01",
        item_type="Gem",
    ),
    "Ruffian's Gauntlet": ItemData(
        classification=IC.useful,
        id=621,
        pool_quantity=1,
        game_name="mid-maj-r-off-01",
        item_type="Gem",
    ),
    "Plebian Gauntlet": ItemData(
        classification=IC.useful,
        id=631,
        pool_quantity=1,
        game_name="mid-maj-r-def-01",
        item_type="Gem",
    ),
    "Brittle Shell": ItemData(
        classification=IC.useful,
        id=641,
        pool_quantity=1,
        game_name="low-maj-l-def-01",
        item_type="Gem",
    ),
    "Light Shell": ItemData(
        classification=IC.useful,
        id=651,
        pool_quantity=1,
        game_name="low-maj-l-off-01",
        item_type="Gem",
    ),
    "Simple Cuirass": ItemData(
        classification=IC.useful,
        id=661,
        pool_quantity=1,
        game_name="low-maj-r-def-01",
        item_type="Gem",
    ),
    "Runner's Cuirass": ItemData(
        classification=IC.useful,
        id=671,
        pool_quantity=1,
        game_name="low-maj-r-off-01",
        item_type="Gem",
    ),
    "Blood Eye Construct": ItemData(
        classification=IC.useful,
        id=700,
        game_name="bp-mel-min-aff",
        item_type="Construct",
    ),
    "Shatter End Construct": ItemData(
        classification=IC.useful,
        id=701,
        game_name="bp-mel-min-breaker",
        item_type="Construct",
    ),
    "Amplifier Construct": ItemData(
        classification=IC.useful,
        id=702,
        game_name="bp-mel-min-ampli",
        item_type="Construct",
    ),
    "Finishing Touch Construct": ItemData(
        classification=IC.useful,
        id=703,
        game_name="bp-mel-finisher",
        item_type="Construct",
    ),
    "Double Trouble Construct": ItemData(
        classification=IC.useful,
        id=704,
        game_name="bp-mel-brkdmg",
        item_type="Construct",
    ),
    "Distant Mark Construct": ItemData(
        classification=IC.useful,
        id=705,
        game_name="bp-rang-min-snip",
        item_type="Construct",
    ),
    "High Ground Construct": ItemData(
        classification=IC.useful,
        id=706,
        game_name="bp-rang-min-highground",
        item_type="Construct",
    ),
    "Fly Swatter Construct": ItemData(
        classification=IC.useful,
        id=707,
        game_name="bp-rng-min-wing",
        item_type="Construct",
    ),
    "Stem Pecker Construct": ItemData(
        classification=IC.useful,
        id=708,
        game_name="bp-rng-min-root",
        item_type="Construct",
    ),
    "Bully Construct": ItemData(
        classification=IC.useful,
        id=709,
        game_name="bp-rng-min-bul",
        item_type="Construct",
    ),
    "Steady Zeal Construct": ItemData(
        classification=IC.useful,
        id=710,
        game_name="bp-rng-min-dp",
        item_type="Construct",
    ),
    "Verdant Guard Construct": ItemData(
        classification=IC.useful,
        id=711,
        game_name="bp-cor-min-defl",
        item_type="Construct",
    ),
    "Libra's Blessing Construct": ItemData(
        classification=IC.useful,
        id=712,
        game_name="bp-cor-min-aether",
        item_type="Construct",
    ),
    "Blood Heart Construct": ItemData(
        classification=IC.useful,
        id=713,
        game_name="bp-cor-min-crit",
        item_type="Construct",
    ),
    "Tireless Boulder Construct": ItemData(
        classification=IC.useful,
        id=714,
        game_name="bp-cor-min-stam",
        item_type="Construct",
    ),
    "Lucky Reflex Construct": ItemData(
        classification=IC.useful,
        id=715,
        game_name="bp-cor-min-critdef",
        item_type="Construct",
    ),
    "Feline's Gaze Construct": ItemData(
        classification=IC.useful,
        id=716,
        game_name="bp-cor-min-hazdef",
        item_type="Construct",
    ),
    "Grit Construct": ItemData(
        classification=IC.useful,
        id=717,
        game_name="bp-cor-min-grit",
        item_type="Construct",
    ),
    "Cleanse Construct": ItemData(
        classification=IC.useful,
        id=718,
        game_name="bp-cor-min-balance",
        item_type="Construct",
    ),
    "Bramble Quake": ItemData(  # Pierce
        classification=IC.useful,
        id=800,
        game_name="phy-mel-grass1",
        item_type="Divine Art",
    ),
    "Verdant Saw": ItemData(  # Slash
        classification=IC.useful,
        id=801,
        game_name="phy-mel-grass2",
        item_type="Divine Art",
    ),
    "Leaf Blades": ItemData(  # Slash
        classification=IC.useful,
        id=802,
        game_name="phy-rgd-status1",
        item_type="Divine Art",
    ),
    "Cragspike Salvo": ItemData(  # Pierce
        classification=IC.useful,
        id=803,
        game_name="phy-rgd-dps1",
        item_type="Divine Art",
    ),
    "Ring of Rocks": ItemData(  # Blunt
        classification=IC.useful,
        id=804,
        game_name="phy-grd-shield1",
        item_type="Divine Art",
    ),
    #"Granite Counterslap": ItemData(
    #    classification=IC.useful,
    #    id=805,
    #    game_name="phy-grd-counter1",
    #    item_type="Divine Art",
    #),
    "Boom Snare": ItemData(  # Blunt
        classification=IC.useful,
        id=806,
        game_name="aet-mel-aoe1",
        item_type="Divine Art",
    ),
    "Zapflash Slash": ItemData(  # Slash
        classification=IC.useful,
        id=807,
        game_name="aet-mel-dps1",
        item_type="Divine Art",
    ),
    "Crack Shock": ItemData(  # Slash
        classification=IC.useful,
        id=808,
        game_name="aet-rgd-status1",
        item_type="Divine Art",
    ),
    "Bolt Barrage": ItemData(  # Pierce
        classification=IC.useful,
        id=809,
        game_name="aet-rgd-beam1",
        item_type="Divine Art",
    ),
    "Stardrop Counter": ItemData(
        classification=IC.useful,
        id=810,
        game_name="aet-grd-evadeAtk",
        item_type="Divine Art",
    ),
    # TODO blueprints
    # TODO Minor gems ?
    # TODO dish recipies
    # TODO Artefacts
}
