"""Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `location_id_map.py` with `loc_name_id`."""

location_name_to_id: dict[str, int] = {
    "Aether.Element": 1,
    "Valley.Hammer": 2,
    "Valley.Chakram": 3,
    "Plains.Kama": 4,
    "Plains.Somu": 5,
    "Plains.Watchtower": 6,
    "Plains.HiddenSteep.West": 7,
    "Plains.HiddenSteep.SouthEast": 8,
    "Plains.HiddenSteep.Hidden": 9,
    "Plains.RiverRoad.Statue": 10,
    "Plains.RiverRoad.NorthEast": 11,
    "Plains.RiverRoad.North": 12,
    "Plains.OldFarm.East": 13,
    "Plains.OldFarm.SouthWest": 14,
    "Plains.OldFarm.West": 15,
    "Plains.NorthBend.North": 16,
    "Plains.RuinedRanch.West": 17,
    "Plains.SouthBend.West": 18,
    "Plains.SouthBend.East": 19,
    "Plains.SouthBend.North": 20,
    "Sundalan.Meridi": 21,
    "Plains.SolGate": 22,
    "Plains.SolGate.Puzzle": 23,
    "Valley.ForkedRoad.East": 24,
    "Valley.ForkedRoad.West": 25,
    "Valley.ForkedRoad.South": 26,
    "Valley.ReaversEnd.North": 27,
    "Valley.ReaversEnd.East": 28,
    "Valley.ReaversEnd.Boss": 29,
    "Valley.EyeRemis": 30,
    "Valley.Kamu.West": 31,
    "Valley.Kamu.NorthEast": 32,
    "Valley.Kamu.South": 33,
    "Valley.Fossil.South": 34,
    "Valley.Fossil.East": 35,
    "Valley.Lumber.EternalSpringChest": 36,
    "Valley.Lumber.West": 37,
    "Valley.Lumber.East": 38,
    "Valley.LyhamnShelter.East": 39,
    "Valley.LyhamnShelter.Combat": 40,
    "EternalSpring.Outside": 41,
    "Valley.Crescent.SouthWest": 42,
    "Valley.ValleyEntrance.Bridge": 43,
    "Valley.ValleyEntrance.East": 44,
    "Valley.DuskApproach.East": 45,
    "Valley.DuskApproach.South": 46,
    "Valley.DuskApproach.West": 47,
    "Valley.CliffSide": 48,
    "Valley.MedianDivide.Middle": 49,
    "Valley.MedianDivide.West": 50,
    "Valley.RedForest.West": 51,
    "Valley.RedForest.South": 52,
    "Valley.Lake.West": 53,
    "Valley.Lake.North": 54,
    "Valley.SilverFileds.North": 55,
    "Valley.HollowIncline.West": 56,
    "Valley.HollowIncline.Middle": 57,
    "Valley.Peak.East": 58,
    "Valley.Peak.West": 59,
    "Valley.RemisRock.West": 60,
    "Valley.RemisRock.North": 61,
    "Valley.RemisRock.East": 62,
    "Valley.RemisRock.NorthEast": 63,
    "Lyhamn.Center.West": 64,
    "Lyhamn.Center.North": 65,
    "Lyhamn.Reef": 66,
    "Lyhamn.Garden.East": 67,
    "Lyhamn.Garden.West": 68,
    "Lyhamn.PentersonOffering": 69,
    "Lyhamn.PetrosOffering": 70,
    "Lyhamn.MarmisOffering": 71,
    "Lyhamn.AlezandaOffering": 72,
    "Lyhamn.OrlandaOffering": 73,
    "EternalSpring.A3": 74,
    "EternalSpring.A5": 75,
    "EternalSpring.A6": 76,
    "Lyhamn.ReefCave": 77,
    "Lyhamn.FoggyLair": 78,
    "Aether.A1": 79,
    "Aether.A2.West": 80,
    "Aether.B4": 81,
    "Aether.A4": 82,
    "Aether.B7": 83,
    "Aether.A2.East": 84,
    "Aether.B5": 85,
    "Basic Ration": 86,
    "Ring Ration": 87,
    "Scrambled Egg": 88,
    "Fried Rice": 89,
    "Ring Rolls": 90,
    "Grilled Salmo": 91,
    "Baked Prapple": 92,
    "Prapple Salad": 93,
    "Pickled Garrot": 94,
    "Garrot Soup": 95,
    "Fisher's Gift": 96,
    "Fieldfruit Bake": 97,
    "Up & Below": 98,
    "Clerry Roll": 99,
    "Frumato Rice": 100,
    "Branching Out": 101,
    "Rice to the Occasion": 102,
    "Blooming Villain": 103,
    "A Sneak Peak": 104,
    "Wheat Field Wack-A-mole": 105,
    "Nuemera Island": 106,
    "Quick Quickwood Query": 107,
    "Temple Incursion": 108,
    "Iron Deficiency": 109,
    "For the Children, right ?": 110,
    "Spring's Return": 111,
    "The Fervor of Youth": 112,
    "Free the Fish": 113,
}
