"""Generated data, DO NOT MODIFY HERE.
Check the `data_extractors` folder to see how to generate this file or to make modifications.
This file got generated in `location_id_map.py` with `loc_name_id`."""

location_name_to_id = {
    "Plains.Somu": 1,
    "Plains.Watchtower": 2,
    "Plains.HiddenSteep.West": 3,
    "Plains.HiddenSteep.SouthEast": 4,
    "Plains.HiddenSteep.Hidden": 5,
    "Plains.RiverRoad.Statue": 6,
    "Plains.RiverRoad.NorthEast": 7,
    "Plains.RiverRoad.North": 8,
    "Plains.OldFarm.East": 9,
    "Plains.OldFarm.SouthWest": 10,
    "Plains.OldFarm.Quest": 11,
    "Plains.NorthBend.North": 12,
    "Plains.RuinedRanch.West": 13,
    "Plains.SouthBend.West": 14,
    "Plains.SouthBend.East": 15,
    "Plains.SouthBend.North": 16,
    "Sundalan.Meridi": 17,
    "Plains.SolGate": 18,
    "Plains.SolGate.Puzzle": 19,
    "Valley.ForkedRoad.East": 20,
    "Valley.ForkedRoad.West": 21,
    "Valley.ForkedRoad.South": 22,
    "Valley.ReaversEnd.North": 23,
    "Valley.ReaversEnd.East": 24,
    "Valley.ReaversEnd.Boss": 25,
    "Valley.EyeRemis": 26,
    "Valley.Kamu.West": 27,
    "Valley.Kamu.NorthEast": 28,
    "Valley.Kamu.South": 29,
    "Valley.Fossil.South": 30,
    "Valley.Fossil.East": 31,
    "Valley.Lumber.EternalSpringChest": 32,
    "Valley.Lumber.West": 33,
    "Valley.Lumber.East": 34,
    "Valley.LyhamnShelter.East": 35,
    "Valley.LyhamnShelter.Combat": 36,
    "EternalSpring.Outside": 37,
    "Valley.Crescent.SouthWest": 38,
    "Valley.ValleyEntrance.Bridge": 39,
    "Valley.ValleyEntrance.East": 40,
    "Valley.DuskApproach.East": 41,
    "Valley.DuskApproach.South": 42,
    "Valley.DuskApproach.West": 43,
    "Valley.CliffSide": 44,
    "Valley.MedianDivide.Middle": 45,
    "Valley.MedianDivide.West": 46,
    "Valley.RedForest.West": 47,
    "Valley.RedForest.South": 48,
    "Valley.Lake.West": 49,
    "Valley.Lake.North": 50,
    "Valley.SilverFileds.North": 51,
    "Valley.HollowIncline.West": 52,
    "Valley.HollowIncline.Middle": 53,
    "Valley.Peak.East": 54,
    "Valley.Peak.West": 55,
    "Valley.RemisRock.West": 56,
    "Valley.RemisRock.North": 57,
    "Valley.RemisRock.East": 58,
    "Valley.RemisRock.NorthEast": 59,
    "Lyhamn.Center.West": 60,
    "Lyhamn.Center.North": 61,
    "Lyhamn.Reef": 62,
    "Lyhamn.Garden.East": 63,
    "Lyhamn.Garden.West": 64,
    "Lyhamn.PentersonOffering": 65,
    "Lyhamn.PetrosOffering": 66,
    "Lyhamn.MarmisOffering": 67,
    "Lyhamn.AlezandaOffering": 68,
    "Lyhamn.OrlandaOffering": 69,
    "EternalSpring.A3": 70,
    "EternalSpring.A5": 71,
    "EternalSpring.A6": 72,
    "Lyhamn.ReefCave": 73,
    "Lyhamn.FoggyLair": 74,
    "Aether.A1": 75,
    "Aether.A2.West": 76,
    "Aether.B4": 77,
    "Aether.A2.NorthEast": 78,
    "Aether.B7": 79,
    "Aether.A2.East": 80,
    "Aether.B5": 81,
    "Branching Out": 82,
    "Rice to the Occasion": 83,
    "Blooming Villain": 84,
    "A Sneak Peak": 85,
    "Wheat Field Wack-A-mole": 86,
    "Nuemera Island": 87,
    "Quick Quickwood Query": 88,
    "Temple Incursion": 89,
    "Iron Deficiency": 90,
    "For the Children, right ?": 91,
    "Spring's Return": 92,
    "The Fervor of Youth": 93,
    "Free the Fish": 94,
    "Basic Ration": 95,
    "Ring Ration": 96,
    "Scrambled Egg": 97,
    "Fried Rice": 98,
    "Ring Rolls": 99,
    "Grilled Salmo": 100,
    "Baked Prapple": 101,
    "Prapple Salad": 102,
    "Pickled Garrot": 103,
    "Garrot Soup": 104,
    "Fisher's Gift": 105,
    "Fieldfruit Bake": 106,
    "Up & Below": 107,
    "Clerry Roll": 108,
    "Frumato Rice": 109,
}
